[사다리 게임] 미르 미션 제출합니다.
wootechco-again-level1/ladder pull request #5
Opened 2019-12-02 15:44 UTC by ddu0422

TDD로 하려니 너무 어렵네요.. ㅠㅠ
많은 피드백 부탁드려요~

2019-12-02 16:46 UTC, pkch93 requested changes
짧은 시간 동안 구현 잘해주셨네요 !
특히 꼼꼼한 테스트, 꼼꼼한 예외처리가 돋보였습니다 :)

제 생각에 조금 의아한 부분이랑 고치면 더 좋을 것 같은 부분 피드백 남겼으니 확인해주세요!
의문이나 궁금한 점 있으면 언제든 물어봐주세요 :)

2019-12-02 16:46 UTC, pkch93 commented on src/main/java/domain/ladder/Ladder.java
> +        validHeight(ladderLines.size());
```suggestion
        validHeight(size());
```
아래 ladderLines.size()를 호출하고 있는 size() 메서드를 호출하는건 어떤가요? 추가로 size라는 메서드 이름보다 height라는 메서드명은 어떤가요?

2019-12-02 16:46 UTC, pkch93 commented on src/main/java/domain/ladder/Ladder.java
> +    public boolean isHasRight(final int height, final int width) {
is나 has는 boolean 필드의 getter로 java에서 주로 사용되는데 두 동사가 함께 쓰이는게 어색하다고 생각하는데 어떤가요?

내 생각은 `isHasRight`가 '오른쪽으로 이동할 수 있는지'를 판단하는 것 같은데 `isMoveRight`나 `canMoveRight` 같은 메서드 명은 어때요?

2019-12-02 16:46 UTC, pkch93 commented on src/main/java/domain/ladder/LadderBridge.java
> +    private final boolean hasRight;
참고: https://www.linkedin.com/pulse/naming-java-boolean-field-method-nazmul-alam
위 참고 자료에 `A field should be an adjective` 문구와 같이 'boolean 필드는 형용사로 명명해야한다'라고 말하고 있어요.

hasLeft, hasRight는 getter에 어울리는 네이밍 같은데 왼쪽, 오른쪽으로 이동할 수 있는 이라는 의미로 `movableLeft`, `movableRight`는 어떤가요?

2019-12-02 16:46 UTC, pkch93 commented on src/main/java/domain/ladder/LadderBridge.java
> +    }
정적 팩토리 메서드 :+1:

2019-12-02 16:46 UTC, pkch93 commented on src/main/java/domain/ladder/LadderBridgeGenerator.java
> +public class LadderBridgeGenerator {
:+1:

2019-12-02 16:46 UTC, pkch93 commented on src/main/java/domain/ladder/LadderGenerator.java
> +                .forEach((index) -> ladderLines.add(LadderLineGenerator.generate(users)));
```suggestion
        IntStream.range(0, height)
                .mapToObj(index -> LadderLineGenerator.generate(users))
                .collect(Collectiors.toList());
```
위와 같이 foreach로 하나씩 담기보다 바로 생성해서 할당하는건 어때요?

2019-12-02 16:46 UTC, pkch93 commented on src/main/java/domain/ladder/LadderLine.java
> +        return Collections.unmodifiableList(ladderBridges);
컬렉션 getter마다 unmodifiableList가 있는 모습이 보기 좋네요 :100:

2019-12-02 16:46 UTC, pkch93 commented on src/main/java/domain/user/User.java
> +        if (ALL.equals(name)) {
`all` 특수 이름에 대한 예외처리 :+1:

2019-12-02 16:46 UTC, pkch93 commented on src/main/java/domain/user/User.java
> +        if (ladderBridges.size() == position) {
LadderLine 클래스가 List<LadderBridge>를 관리하는 것 같은데 ladderline 객체에 메세지를 보내서 마지막 위치인지 확인하는게 어떤가요?

```suggestion
	public User move(final LadderLine ladderline) {
        if (ladderline.isLastPosition(position)) {
```
만약 구현하게 된다면 위와 같은 모습이 될 거 같네요. :) move를 사용하고 있는 부분을 타고 넘어갔을 때 LadderGame의 move가 나오는데 여기서 `ladderline.getLadderBridges()`를 부르고 있는걸로 봐서 충분히 위 방식으로 구현할 수 있을거라 생각합니다!

2019-12-02 16:46 UTC, pkch93 commented on src/main/java/domain/user/Users.java
> +        return new Users(users.stream()
여기는 unmodifiableList가 없네요 ㅠㅠ

2019-12-02 16:46 UTC, pkch93 commented on src/main/java/domain/user/UsersGenerator.java
> +        int count = (int) names.stream()
중복 이름 예외처리 :+1:

2019-12-02 16:46 UTC, pkch93 commented on src/main/java/presentation/LadderController.java
> +        outputResult(ladderGame);
이 부분은 InputView와 OutputView의 역할을 컨트롤러가 하는 것 같네요. 보고 싶은 결과를 사용자에게 받고 받은 값을 OutputView에 넘겨서 컨트롤러에 결과 출력 로직을 없앨 수 있을거 같아요.

2019-12-03 03:53 UTC, ddu0422 commented on src/main/java/domain/ladder/Ladder.java
> +        validHeight(ladderLines.size());
짜잔~ ladderLine.size()는 매개변수였습니다.

2019-12-03 15:08 UTC, ddu0422 commented on src/main/java/domain/ladder/Ladder.java
> +        validHeight(ladderLines.size());
height라는 메서드명이 더 보기 좋겠네요 ^^

2019-12-03 15:09 UTC, ddu0422 commented on src/main/java/domain/ladder/Ladder.java
> +    public boolean isHasRight(final int height, final int width) {
좋은 생각입니다. 
뭔가 이상하긴 했는데 좋은 생각이 안났어요 :)

2019-12-03 15:12 UTC, ddu0422 commented on src/main/java/domain/ladder/LadderBridge.java
> +    private final boolean hasRight;
좋은글 감사합니다 ㅎㅎ

2019-12-03 15:20 UTC, ddu0422 commented on src/main/java/domain/ladder/LadderGenerator.java
> +                .forEach((index) -> ladderLines.add(LadderLineGenerator.generate(users)));
어떻게 할까 생각하다가 잠들었는데 좋은 정보 감사합니다 ㅎㅎ

2019-12-03 15:23 UTC, ddu0422 commented on src/main/java/domain/user/Users.java
> +        return new Users(users.stream()
이 부분은 생성자로 넣어줘서 안해도 되겠다라는 생각이 들어 해당 구문을 작성하지 않았습니다.
하지만 더 생각을 해보니 작성하는게 더 좋아보이네요 :)

2019-12-03 15:43 UTC, ddu0422 commented
좋은 리뷰 감사합니다 :)

2019-12-04 01:40 UTC, pkch93 commented
보다 보기 좋은 코드가 됐네요 :) 한가지 아쉬운 부분만 코멘트 남기고 머지할께요 고생하셨습니다 ~!

2019-12-04 01:40 UTC, merged

2019-12-04 01:45 UTC, pkch93 commented
아 피드백이 안남겨져서 다시 남깁니다. Application에서 InputView로 결과를 받아보고픈 유저의 이름을 받고 Controller로 최종 결과를 도출, OutputView가 Controller에게서 받은 결과를 출력하도록 역할을 분리하면 좋을 것 같아요 :)